### ISSUE TITLE
About Texts starting with Turkish characters

### ISSUE THREAD

**Issue by sametgu** [boratuncer/exnotes#15]
Hi,

Texts starting with Turkish characters, it cannot be saved when it is written into the note.

Best regards

**Comment by boratuncer** [comment]
Problem is solved.

**Comment by sametgu** [comment]
Hi,
1- After clicking adding new note button and to write "ıstanbul", to press enter key.
2-After double-clicking new note (ıstanbul) to write text starting Turkish characters.
3- After pressing save button you will see errors like attached picture.

Best regards.

![13](https://user-images.githubusercontent.com/53643595/64066538-c4d92e80-cc23-11e9-98fb-5e70369e0cca.PNG)
![14](https://user-images.githubusercontent.com/53643595/64066542-ce629680-cc23-11e9-9796-26444d3bbc44.PNG)
![15](https://user-images.githubusercontent.com/53643595/64066543-cefb2d00-cc23-11e9-88c8-12beefaec3b1.PNG)
![16](https://user-images.githubusercontent.com/53643595/64066544-cefb2d00-cc23-11e9-9179-89cfad7f17fd.PNG)

**Comment by boratuncer** [comment]
Could you please put pictures step by step next time ?

It is not easy to understand what picture is for what demo.

**Comment by boratuncer** [comment]
Problem is solved in V1.0.6.
