### ISSUE TITLE
about errors received, after writing Header texts starting with Turkish characters

### ISSUE THREAD

**Issue by sametgu** [boratuncer/exnotes#17]
Hi,

1-entered into the category
2-created a new note
3-after creating a new note entered into it.
4-After writing texts starting with Turkish characters, pressing save button.
5-you will see different errors like attached pictures.

Best regards.

![5](https://user-images.githubusercontent.com/53643595/63442713-42d75180-c43c-11e9-88c6-dfde1125601c.PNG)
![6](https://user-images.githubusercontent.com/53643595/63442714-436fe800-c43c-11e9-845f-7ff3d1ce8d03.PNG)
![7](https://user-images.githubusercontent.com/53643595/63442715-436fe800-c43c-11e9-9cb8-8a97c62d4641.PNG)
![8](https://user-images.githubusercontent.com/53643595/63442718-44087e80-c43c-11e9-9140-8c9d5d789fa2.PNG)

**Comment by boratuncer** [comment]
#7 'nin kopyası.

Problem V1.0.5'te çözüldü.
