### ISSUE TITLE
After narrowing main page from left or right during note body is opened, it can't auto-size  body text

### ISSUE THREAD

**Issue by sametgu** [boratuncer/exnotes#19]
Hi,

After narrowing main page from left or right during note body is opened, it can't auto-size body text.

Best regards.
![9](https://user-images.githubusercontent.com/53643595/63511431-e29ee900-c4e9-11e9-9f8a-74d3d6ae5792.PNG)
![10](https://user-images.githubusercontent.com/53643595/63511432-e29ee900-c4e9-11e9-890c-e081c32ee9e5.PNG)

**Comment by boratuncer** [comment]
Proje Microsoft Devops'a taşındığı için tickte oradan devam edilecek.
