### ISSUE TITLE
Crash after pressing test connection button

### ISSUE THREAD

**Issue by sametgu** [boratuncer/exnotes#2]
Hi,

My application crashes after pressing test connect button.

V1.0.4

Best regards.

**Comment by boratuncer** [comment]
Are there any details from Windows events ?

**Comment by sametgu** [comment]
Detailed Error information is as below.

https://windows-hexerror.linestarve.com/0x800F1000 

Fault bucket 1716598199976126119, type 5
Event Name: POFContextAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: ExNotes_1.0.4.0_x86__06wy4fzd63a5c
P2: praid:App
P3: 1.0.4.0
P4: 0x800f1000
P5: 39bf9dd5a38d0ccccd9de1db44cf5293
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\sametgu\AppData\Local\Packages\exnotes_06wy4fzd63a5c\AC\GEH\POF-11556.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB18C.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB3C0.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB40D.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB46B.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_ExNotes_1.0.4.0__7b9b42a86e8c917b15a5d5ced630dfed9a639b_00000000_3513d65a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 510ad61e-549a-4b54-9658-a38a828ad91d
Report Status: 268435456
Hashed bucket: fbffd182de11d27f17d294f7cba6e6a7
Cab Guid: 0

**Comment by boratuncer** [comment]
There is no valuable information here, do you have any other data ?

**Comment by sametgu** [comment]
While "ExNote" install with PowerShell,  if you choose "Y"(yes) at policy settings, popup doesn't work. If you choose "A" (all) at policy setting, popup works.

After pressing test connection button program crashed again. I guess it is a different problem.

![11](https://user-images.githubusercontent.com/53643595/63620879-377e5480-c5fb-11e9-941b-fc6e7c8f2708.PNG)
![12](https://user-images.githubusercontent.com/53643595/63623355-0f462400-c602-11e9-8371-2cab645deb9a.PNG)

**Comment by boratuncer** [comment]
Problem is solved.
