### ISSUE TITLE
Türkçe büyük Harf  karakterleri gösterilemiyor.

### ISSUE THREAD

**Issue by sametgu** [boratuncer/exnotes#22]
Merahbalar,

Not içeriğinde "ŞĞÜÖÇ" karakterleri  var ise gösterilemiyor.

İyi çalışamalar.

**Comment by sametgu** [comment]
![Türkçe büyük harf](https://user-images.githubusercontent.com/53643595/71071114-0f5bc800-218d-11ea-8869-41929298318d.PNG)

**Comment by boratuncer** [comment]
Proje Microsoft Devops'a taşındığı için tickte oradan devam edilecek.
