### ISSUE TITLE
Katagoride aranacak kelime arama alanına yazılıp enter tuşlanınca program kapanıyor.

### ISSUE THREAD

**Issue by sametgu** [boratuncer/exnotes#24]
Merhabalar,

Katagoride aranacak kelime yazılıp enter tuşlanınca program kapanıyor.

Arama simgesine basıldığında da arama yapılması için açılan alanı kapatıyor.

Bu simgeye basıldığında yazılan kelimenin içeriğinin geçtiği notları bulması bekleniyor.

Konuyla ilgili yardımlarnızı rica ederiz.

**Comment by sametgu** [comment]
![arama](https://user-images.githubusercontent.com/53643595/71079613-a67c4c00-219c-11ea-9ec3-be71057b6974.PNG)

**Comment by sametgu** [comment]
![arama1](https://user-images.githubusercontent.com/53643595/71079716-d166a000-219c-11ea-9306-4f6e842f9c35.PNG)

**Comment by boratuncer** [comment]
Proje Microsoft Devops'a taşındığı için tickte oradan devam edilecek.
