### ISSUE TITLE
Opening screen

### ISSUE THREAD

**Issue by sametgu** [boratuncer/exnotes#9]
Hi,

Ffter opening ExNote, settings window appear above status window.

Best regards
![1](https://user-images.githubusercontent.com/53643595/63416356-f2de9780-c407-11e9-95c0-65bfed405b68.PNG)

**Comment by boratuncer** [comment]
I could not reproduce it.

**Comment by boratuncer** [comment]
Proje Microsoft Devops'a taşındığı için tickte oradan devam edilecek.
